### PR TITLE
- Furthered story

### PR DESCRIPTION
**Pull request by Karlahaigh**
- Created context of the world with holoterminals

### CODE REVIEW

**Comment by Karlahaigh** [comment]
small changes made to correct grammar, improve flow. If you disagree please let me know as I can change them back.

**Comment by Karlahaigh** [comment]
Oh! otherwise, I would say please go ahead and merge 'cause it's great!

**Comment by udomugo** [comment]
I think the changes look great. Thanks for looking over the grammar, that is not my strong suit.

**Comment by Karlahaigh** [comment]
Gracias :) would you be so kind as to merge then then? Thanks!

**Comment by Karlahaigh** [comment]
Great! Thanks!

**Pull request merged**
